/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SecretStorageDemoPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/storage.ts
var import_obsidian = require("obsidian");

// src/crypto.ts
var _CryptoService = class {
  /**
   * 生成随机盐值
   */
  generateSalt() {
    return crypto.getRandomValues(new Uint8Array(_CryptoService.SALT_LENGTH));
  }
  /**
   * 生成随机 IV
   */
  generateIV() {
    return crypto.getRandomValues(new Uint8Array(_CryptoService.IV_LENGTH));
  }
  /**
   * 生成设备 ID
   */
  generateDeviceId() {
    const bytes = crypto.getRandomValues(new Uint8Array(8));
    return "device-" + this.arrayBufferToBase64(bytes.buffer).replace(/[+/=]/g, "").slice(0, 12);
  }
  /**
   * 从密码派生加密密钥
   * @param password 用户主密码
   * @param salt 盐值
   * @returns CryptoKey 对象
   */
  async deriveKey(password, salt) {
    const encoder = new TextEncoder();
    const keyMaterial = await crypto.subtle.importKey(
      "raw",
      encoder.encode(password),
      "PBKDF2",
      false,
      ["deriveKey"]
    );
    return crypto.subtle.deriveKey(
      {
        name: "PBKDF2",
        salt,
        iterations: _CryptoService.ITERATIONS,
        hash: "SHA-256"
      },
      keyMaterial,
      { name: "AES-GCM", length: _CryptoService.KEY_LENGTH },
      false,
      // 不可导出
      ["encrypt", "decrypt"]
    );
  }
  /**
   * 加密数据
   * @param data 要加密的字符串
   * @param key 加密密钥
   * @returns IV 和密文
   */
  async encrypt(data, key) {
    const iv = this.generateIV();
    const encoder = new TextEncoder();
    const ciphertext = await crypto.subtle.encrypt(
      { name: "AES-GCM", iv },
      key,
      encoder.encode(data)
    );
    return { iv, ciphertext };
  }
  /**
   * 解密数据
   * @param ciphertext 密文
   * @param key 解密密钥
   * @param iv 初始化向量
   * @returns 解密后的字符串
   */
  async decrypt(ciphertext, key, iv) {
    const decrypted = await crypto.subtle.decrypt(
      { name: "AES-GCM", iv },
      key,
      ciphertext
    );
    return new TextDecoder().decode(decrypted);
  }
  /**
   * 创建密码验证器
   * 用于快速验证密码是否正确，而不需要解密整个数据
   */
  async createVerifier(key) {
    const iv = this.generateIV();
    const encoder = new TextEncoder();
    const verifier = await crypto.subtle.encrypt(
      { name: "AES-GCM", iv },
      key,
      encoder.encode(_CryptoService.VERIFIER_PLAINTEXT)
    );
    return { iv, verifier };
  }
  /**
   * 验证密码是否正确
   */
  async verifyPassword(key, iv, verifier) {
    try {
      const decrypted = await crypto.subtle.decrypt(
        { name: "AES-GCM", iv },
        key,
        verifier
      );
      const text = new TextDecoder().decode(decrypted);
      return text === _CryptoService.VERIFIER_PLAINTEXT;
    } catch (e) {
      return false;
    }
  }
  /**
   * 创建加密的密钥库
   */
  async createEncryptedVault(password, secrets, deviceId) {
    const salt = this.generateSalt();
    const key = await this.deriveKey(password, salt);
    const { iv: verifierIv, verifier } = await this.createVerifier(key);
    const secretsData = {
      secrets,
      metadata: {
        createdAt: new Date().toISOString(),
        modifiedAt: new Date().toISOString(),
        version: 1
      }
    };
    const { iv, ciphertext } = await this.encrypt(JSON.stringify(secretsData), key);
    return {
      version: 2,
      algorithm: "AES-256-GCM",
      kdf: "PBKDF2",
      kdfIterations: _CryptoService.ITERATIONS,
      salt: this.arrayBufferToBase64(salt.buffer),
      iv: this.arrayBufferToBase64(iv.buffer),
      verifier: this.arrayBufferToBase64(verifierIv.buffer) + ":" + this.arrayBufferToBase64(verifier),
      data: this.arrayBufferToBase64(ciphertext),
      lastModified: new Date().toISOString(),
      deviceId
    };
  }
  /**
   * 解密密钥库
   */
  async decryptVault(vault, password) {
    try {
      const salt = this.base64ToUint8Array(vault.salt);
      const key = await this.deriveKey(password, salt);
      const [verifierIvBase64, verifierBase64] = vault.verifier.split(":");
      const verifierIv = this.base64ToUint8Array(verifierIvBase64);
      const verifier = this.base64ToArrayBuffer(verifierBase64);
      const isValid = await this.verifyPassword(key, verifierIv, verifier);
      if (!isValid) {
        return null;
      }
      const iv = this.base64ToUint8Array(vault.iv);
      const ciphertext = this.base64ToArrayBuffer(vault.data);
      const decrypted = await this.decrypt(ciphertext, key, iv);
      return JSON.parse(decrypted);
    } catch (error) {
      console.error("Vault decryption failed:", error);
      return null;
    }
  }
  /**
   * 更新加密的密钥库（保持相同的 salt，重新加密）
   */
  async updateEncryptedVault(vault, password, secrets, deviceId) {
    try {
      const salt = this.base64ToUint8Array(vault.salt);
      const key = await this.deriveKey(password, salt);
      const [verifierIvBase64, verifierBase64] = vault.verifier.split(":");
      const verifierIv = this.base64ToUint8Array(verifierIvBase64);
      const verifierData = this.base64ToArrayBuffer(verifierBase64);
      const isValid = await this.verifyPassword(key, verifierIv, verifierData);
      if (!isValid) {
        return null;
      }
      const secretsData = {
        secrets,
        metadata: {
          createdAt: vault.lastModified,
          // 保持原创建时间
          modifiedAt: new Date().toISOString(),
          version: (vault.version || 1) + 1
        }
      };
      const { iv, ciphertext } = await this.encrypt(JSON.stringify(secretsData), key);
      return {
        ...vault,
        iv: this.arrayBufferToBase64(iv.buffer),
        data: this.arrayBufferToBase64(ciphertext),
        lastModified: new Date().toISOString(),
        deviceId
      };
    } catch (error) {
      console.error("Vault update failed:", error);
      return null;
    }
  }
  /**
   * 修改主密码
   */
  async changePassword(vault, oldPassword, newPassword, deviceId) {
    const secretsData = await this.decryptVault(vault, oldPassword);
    if (!secretsData) {
      return null;
    }
    return this.createEncryptedVault(newPassword, secretsData.secrets, deviceId);
  }
  // ============================================
  // 工具方法
  // ============================================
  /**
   * ArrayBuffer 转 Base64
   */
  arrayBufferToBase64(buffer) {
    const bytes = new Uint8Array(buffer);
    let binary = "";
    for (let i = 0; i < bytes.byteLength; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary);
  }
  /**
   * Base64 转 Uint8Array
   */
  base64ToUint8Array(base64) {
    const binary = atob(base64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) {
      bytes[i] = binary.charCodeAt(i);
    }
    return bytes;
  }
  /**
   * Base64 转 ArrayBuffer
   */
  base64ToArrayBuffer(base64) {
    return this.base64ToUint8Array(base64).buffer;
  }
};
var CryptoService = _CryptoService;
// OWASP 2023 推荐的 PBKDF2 迭代次数
CryptoService.ITERATIONS = 31e4;
CryptoService.KEY_LENGTH = 256;
CryptoService.SALT_LENGTH = 16;
// 128 bits
CryptoService.IV_LENGTH = 12;
// 96 bits (GCM 推荐)
CryptoService.VERIFIER_PLAINTEXT = "obsidian-secret-storage-v2";
var cryptoService = new CryptoService();

// src/storage.ts
var LocalStorageProvider = class {
  constructor(app) {
    this.app = app;
  }
  async save(id, secret) {
    try {
      this.app.secretStorage.setSecret(id, secret);
      return true;
    } catch (error) {
      console.error("LocalStorageProvider save error:", error);
      return false;
    }
  }
  async get(id) {
    try {
      return this.app.secretStorage.getSecret(id) || null;
    } catch (error) {
      console.error("LocalStorageProvider get error:", error);
      return null;
    }
  }
  async list() {
    try {
      return this.app.secretStorage.listSecrets();
    } catch (error) {
      console.error("LocalStorageProvider list error:", error);
      return [];
    }
  }
  async delete(id) {
    try {
      this.app.secretStorage.setSecret(id, "");
      return true;
    } catch (error) {
      console.error("LocalStorageProvider delete error:", error);
      return false;
    }
  }
  isUnlocked() {
    return true;
  }
  getMode() {
    return "local";
  }
};
var SyncStorageProvider = class {
  constructor(app, autoLockMinutes = 30) {
    // 运行时状态
    this.unlocked = false;
    this.secrets = {};
    this.vault = null;
    this.encryptionKey = null;
    this.password = null;
    // 自动锁定定时器
    this.lockTimer = null;
    this.autoLockTimeout = 30 * 60 * 1e3;
    // 默认 30 分钟
    // 文件路径
    this.VAULT_FILE = "secrets.enc";
    this.BACKUP_DIR = "backups";
    // 冲突状态
    this.conflictRemoteVault = null;
    this.conflictRemoteSecrets = null;
    this.conflictCallback = null;
    this.app = app;
    this.crypto = cryptoService;
    this.deviceId = this.getOrCreateDeviceId();
    this.autoLockTimeout = autoLockMinutes * 60 * 1e3;
  }
  /**
   * 获取或创建设备 ID
   */
  getOrCreateDeviceId() {
    const key = "secret-storage-device-id";
    let deviceId = localStorage.getItem(key);
    if (!deviceId) {
      deviceId = this.crypto.generateDeviceId();
      localStorage.setItem(key, deviceId);
    }
    return deviceId;
  }
  /**
   * 获取插件数据目录路径
   */
  getPluginDir() {
    return `${this.app.vault.configDir}/plugins/secret-storage-demo`;
  }
  /**
   * 获取密钥库文件路径
   */
  getVaultPath() {
    return `${this.getPluginDir()}/${this.VAULT_FILE}`;
  }
  /**
   * 获取备份目录路径
   */
  getBackupDir() {
    return `${this.getPluginDir()}/${this.BACKUP_DIR}`;
  }
  /**
   * 检查密钥库是否已初始化
   */
  async isInitialized() {
    try {
      const exists = await this.app.vault.adapter.exists(this.getVaultPath());
      return exists;
    } catch (e) {
      return false;
    }
  }
  /**
   * 初始化密钥库（首次设置密码）
   */
  async initialize(password) {
    try {
      const vault = await this.crypto.createEncryptedVault(password, {}, this.deviceId);
      const pluginDir = this.getPluginDir();
      if (!await this.app.vault.adapter.exists(pluginDir)) {
        await this.app.vault.adapter.mkdir(pluginDir);
      }
      await this.app.vault.adapter.write(
        this.getVaultPath(),
        JSON.stringify(vault, null, 2)
      );
      this.vault = vault;
      this.secrets = {};
      this.password = password;
      this.unlocked = true;
      this.resetLockTimer();
      return true;
    } catch (error) {
      console.error("SyncStorageProvider initialize error:", error);
      return false;
    }
  }
  /**
   * 解锁密钥库
   */
  async unlock(password) {
    try {
      const content = await this.app.vault.adapter.read(this.getVaultPath());
      const vault = JSON.parse(content);
      const secretsData = await this.crypto.decryptVault(vault, password);
      if (!secretsData) {
        return false;
      }
      this.vault = vault;
      this.secrets = secretsData.secrets;
      this.password = password;
      this.unlocked = true;
      this.resetLockTimer();
      return true;
    } catch (error) {
      console.error("SyncStorageProvider unlock error:", error);
      return false;
    }
  }
  /**
   * 锁定密钥库
   */
  lock() {
    this.unlocked = false;
    this.secrets = {};
    this.encryptionKey = null;
    this.password = null;
    if (this.lockTimer) {
      clearTimeout(this.lockTimer);
      this.lockTimer = null;
    }
  }
  /**
   * 重置自动锁定定时器
   */
  resetLockTimer() {
    if (this.lockTimer) {
      clearTimeout(this.lockTimer);
    }
    if (this.autoLockTimeout > 0) {
      this.lockTimer = setTimeout(() => {
        this.lock();
        new import_obsidian.Notice("\u{1F512} \u5BC6\u94A5\u5E93\u5DF2\u81EA\u52A8\u9501\u5B9A");
      }, this.autoLockTimeout);
    }
  }
  /**
   * 保存密钥
   */
  async save(id, secret) {
    if (!this.unlocked || !this.password) {
      new import_obsidian.Notice("\u26A0\uFE0F \u8BF7\u5148\u89E3\u9501\u5BC6\u94A5\u5E93");
      return false;
    }
    try {
      this.secrets[id] = secret;
      await this.persistSecrets();
      this.resetLockTimer();
      return true;
    } catch (error) {
      console.error("SyncStorageProvider save error:", error);
      return false;
    }
  }
  /**
   * 获取密钥
   */
  async get(id) {
    if (!this.unlocked) {
      return null;
    }
    this.resetLockTimer();
    return this.secrets[id] || null;
  }
  /**
   * 列出所有密钥 ID
   */
  async list() {
    if (!this.unlocked) {
      return [];
    }
    this.resetLockTimer();
    return Object.keys(this.secrets).filter((id) => this.secrets[id] !== "");
  }
  /**
   * 删除密钥
   */
  async delete(id) {
    if (!this.unlocked || !this.password) {
      new import_obsidian.Notice("\u26A0\uFE0F \u8BF7\u5148\u89E3\u9501\u5BC6\u94A5\u5E93");
      return false;
    }
    try {
      delete this.secrets[id];
      await this.persistSecrets();
      this.resetLockTimer();
      return true;
    } catch (error) {
      console.error("SyncStorageProvider delete error:", error);
      return false;
    }
  }
  /**
   * 持久化密钥到文件
   */
  async persistSecrets() {
    if (!this.vault || !this.password) {
      throw new Error("Vault not initialized");
    }
    await this.createBackup();
    const updatedVault = await this.crypto.updateEncryptedVault(
      this.vault,
      this.password,
      this.secrets,
      this.deviceId
    );
    if (!updatedVault) {
      throw new Error("Failed to update vault");
    }
    await this.app.vault.adapter.write(
      this.getVaultPath(),
      JSON.stringify(updatedVault, null, 2)
    );
    this.vault = updatedVault;
  }
  /**
   * 创建备份
   */
  async createBackup() {
    try {
      const backupDir = this.getBackupDir();
      if (!await this.app.vault.adapter.exists(backupDir)) {
        await this.app.vault.adapter.mkdir(backupDir);
      }
      const vaultPath = this.getVaultPath();
      if (await this.app.vault.adapter.exists(vaultPath)) {
        const content = await this.app.vault.adapter.read(vaultPath);
        const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
        const backupPath = `${backupDir}/secrets.${timestamp}.enc`;
        await this.app.vault.adapter.write(backupPath, content);
        await this.cleanupBackups(5);
      }
    } catch (error) {
      console.error("Backup creation failed:", error);
    }
  }
  /**
   * 清理旧备份
   */
  async cleanupBackups(keepCount) {
    try {
      const backupDir = this.getBackupDir();
      const files = await this.app.vault.adapter.list(backupDir);
      const backups = files.files.filter((f) => f.endsWith(".enc")).sort().reverse();
      for (let i = keepCount; i < backups.length; i++) {
        await this.app.vault.adapter.remove(backups[i]);
      }
    } catch (error) {
      console.error("Backup cleanup failed:", error);
    }
  }
  /**
   * 修改主密码
   */
  async changePassword(oldPassword, newPassword) {
    if (!this.vault) {
      return false;
    }
    const backupVault = this.vault;
    const backupPassword = this.password;
    try {
      await this.createBackup();
      const newVault = await this.crypto.changePassword(
        this.vault,
        oldPassword,
        newPassword,
        this.deviceId
      );
      if (!newVault) {
        return false;
      }
      await this.app.vault.adapter.write(
        this.getVaultPath(),
        JSON.stringify(newVault, null, 2)
      );
      this.vault = newVault;
      this.password = newPassword;
      return true;
    } catch (error) {
      this.vault = backupVault;
      this.password = backupPassword;
      console.error("Password change failed:", error);
      return false;
    }
  }
  isUnlocked() {
    return this.unlocked;
  }
  getMode() {
    return "sync";
  }
  /**
   * 获取密钥库信息
   */
  getVaultInfo() {
    if (!this.vault) {
      return null;
    }
    return {
      lastModified: this.vault.lastModified,
      deviceId: this.vault.deviceId
    };
  }
  /**
   * 设置自动锁定超时时间
   */
  setAutoLockTimeout(minutes) {
    this.autoLockTimeout = minutes * 60 * 1e3;
    if (this.unlocked) {
      this.resetLockTimer();
    }
  }
  /**
   * 从本地模式迁移密钥
   */
  async migrateFromLocal(localSecrets) {
    if (!this.unlocked || !this.password) {
      return false;
    }
    try {
      this.secrets = { ...this.secrets, ...localSecrets };
      await this.persistSecrets();
      return true;
    } catch (error) {
      console.error("Migration failed:", error);
      return false;
    }
  }
  /**
   * 导出所有密钥（用于迁移到本地模式）
   */
  exportSecrets() {
    if (!this.unlocked) {
      return {};
    }
    return { ...this.secrets };
  }
  /**
   * 冲突信息
   */
  getConflictInfo() {
    if (!this.vault || !this.conflictRemoteVault) {
      return null;
    }
    return {
      localVault: this.vault,
      remoteVault: this.conflictRemoteVault,
      localSecrets: Object.keys(this.secrets),
      remoteSecrets: this.conflictRemoteSecrets ? Object.keys(this.conflictRemoteSecrets) : []
    };
  }
  /**
   * 检测同步冲突
   * 在解锁时调用，比较内存中的版本和文件系统中的版本
   */
  async detectConflict() {
    if (!this.vault) {
      return "none";
    }
    try {
      const vaultPath = this.getVaultPath();
      if (!await this.app.vault.adapter.exists(vaultPath)) {
        return "none";
      }
      const remoteContent = await this.app.vault.adapter.read(vaultPath);
      const remoteVault = JSON.parse(remoteContent);
      const localTime = new Date(this.vault.lastModified).getTime();
      const remoteTime = new Date(remoteVault.lastModified).getTime();
      if (localTime === remoteTime) {
        return "none";
      }
      if (this.vault.deviceId === remoteVault.deviceId) {
        return localTime > remoteTime ? "local-newer" : "remote-newer";
      }
      this.conflictRemoteVault = remoteVault;
      if (this.password) {
        const remoteData = await this.crypto.decryptVault(remoteVault, this.password);
        if (remoteData) {
          this.conflictRemoteSecrets = remoteData.secrets;
        }
      }
      return "conflict";
    } catch (error) {
      console.error("Conflict detection failed:", error);
      return "none";
    }
  }
  /**
   * 在保存前检测冲突
   * 返回是否可以继续保存
   */
  async checkBeforeSave() {
    const conflictType = await this.detectConflict();
    switch (conflictType) {
      case "none":
      case "local-newer":
        return { canSave: true, conflictType };
      case "remote-newer":
        return { canSave: false, conflictType };
      case "conflict":
        return { canSave: false, conflictType };
      default:
        return { canSave: true, conflictType: "none" };
    }
  }
  /**
   * 解决冲突 - 使用本地版本
   */
  async resolveConflictWithLocal() {
    if (!this.unlocked || !this.password || !this.vault) {
      return false;
    }
    try {
      await this.persistSecrets();
      this.clearConflictState();
      return true;
    } catch (error) {
      console.error("Resolve conflict with local failed:", error);
      return false;
    }
  }
  /**
   * 解决冲突 - 使用远程版本
   */
  async resolveConflictWithRemote() {
    if (!this.password || !this.conflictRemoteVault) {
      return false;
    }
    try {
      const remoteData = await this.crypto.decryptVault(this.conflictRemoteVault, this.password);
      if (!remoteData) {
        return false;
      }
      this.vault = this.conflictRemoteVault;
      this.secrets = remoteData.secrets;
      this.clearConflictState();
      return true;
    } catch (error) {
      console.error("Resolve conflict with remote failed:", error);
      return false;
    }
  }
  /**
   * 解决冲突 - 合并两个版本
   * 策略: 保留两边所有的密钥，如果同一 ID 存在不同值，保留较新的
   */
  async resolveConflictWithMerge() {
    if (!this.unlocked || !this.password || !this.vault || !this.conflictRemoteVault) {
      return false;
    }
    try {
      const remoteData = await this.crypto.decryptVault(this.conflictRemoteVault, this.password);
      if (!remoteData) {
        return false;
      }
      const localTime = new Date(this.vault.lastModified).getTime();
      const remoteTime = new Date(this.conflictRemoteVault.lastModified).getTime();
      const mergedSecrets = {};
      const allIds = /* @__PURE__ */ new Set([
        ...Object.keys(this.secrets),
        ...Object.keys(remoteData.secrets)
      ]);
      for (const id of allIds) {
        const localValue = this.secrets[id];
        const remoteValue = remoteData.secrets[id];
        if (localValue && remoteValue) {
          mergedSecrets[id] = localTime >= remoteTime ? localValue : remoteValue;
        } else if (localValue) {
          mergedSecrets[id] = localValue;
        } else if (remoteValue) {
          mergedSecrets[id] = remoteValue;
        }
      }
      this.secrets = mergedSecrets;
      await this.persistSecrets();
      this.clearConflictState();
      return true;
    } catch (error) {
      console.error("Resolve conflict with merge failed:", error);
      return false;
    }
  }
  /**
   * 清除冲突状态
   */
  clearConflictState() {
    this.conflictRemoteVault = null;
    this.conflictRemoteSecrets = null;
    this.conflictCallback = null;
  }
  /**
   * 检查是否有待解决的冲突
   */
  hasConflict() {
    return this.conflictRemoteVault !== null;
  }
  /**
   * 刷新密钥库 - 从文件重新加载
   * 用于检测远程同步后的变化
   */
  async refresh() {
    if (!this.unlocked || !this.password) {
      return "none";
    }
    const conflictType = await this.detectConflict();
    if (conflictType === "remote-newer") {
      const content = await this.app.vault.adapter.read(this.getVaultPath());
      const remoteVault = JSON.parse(content);
      const remoteData = await this.crypto.decryptVault(remoteVault, this.password);
      if (remoteData) {
        this.vault = remoteVault;
        this.secrets = remoteData.secrets;
      }
    }
    return conflictType;
  }
};
// ============================================
// 冲突检测与解决 (Phase 4.3, 4.4)
// ============================================
/**
 * 冲突检测结果类型
 */
SyncStorageProvider.ConflictType = {
  NONE: "none",
  // 无冲突
  LOCAL_NEWER: "local-newer",
  // 本地版本更新
  REMOTE_NEWER: "remote-newer",
  // 远程版本更新
  CONFLICT: "conflict"
  // 真正的冲突（不同设备同时修改）
};
function createStorageProvider(app, mode, autoLockMinutes = 30) {
  if (mode === "sync") {
    return new SyncStorageProvider(app, autoLockMinutes);
  }
  return new LocalStorageProvider(app);
}

// src/ui.ts
var import_obsidian2 = require("obsidian");
function evaluatePasswordStrength(password) {
  let score = 0;
  const feedback = [];
  if (password.length >= 8)
    score++;
  if (password.length >= 12)
    score++;
  if (password.length >= 16)
    score++;
  if (password.length < 12) {
    feedback.push("\u5EFA\u8BAE\u4F7F\u7528\u81F3\u5C11 12 \u4E2A\u5B57\u7B26");
  }
  if (/[a-z]/.test(password))
    score += 0.25;
  if (/[A-Z]/.test(password))
    score += 0.25;
  if (/[0-9]/.test(password))
    score += 0.25;
  if (/[^a-zA-Z0-9]/.test(password))
    score += 0.25;
  if (!/[A-Z]/.test(password)) {
    feedback.push("\u6DFB\u52A0\u5927\u5199\u5B57\u6BCD");
  }
  if (!/[0-9]/.test(password)) {
    feedback.push("\u6DFB\u52A0\u6570\u5B57");
  }
  if (!/[^a-zA-Z0-9]/.test(password)) {
    feedback.push("\u6DFB\u52A0\u7279\u6B8A\u5B57\u7B26");
  }
  const commonPatterns = [
    /^123456/,
    /password/i,
    /qwerty/i,
    /^111111/,
    /^000000/
  ];
  for (const pattern of commonPatterns) {
    if (pattern.test(password)) {
      score = Math.max(0, score - 1);
      feedback.push("\u907F\u514D\u4F7F\u7528\u5E38\u89C1\u5BC6\u7801");
      break;
    }
  }
  score = Math.min(4, Math.max(0, Math.floor(score)));
  const labels = ["\u975E\u5E38\u5F31", "\u5F31", "\u4E00\u822C", "\u5F3A", "\u975E\u5E38\u5F3A"];
  const colors = ["#ff4444", "#ff8800", "#ffcc00", "#88cc00", "#00cc44"];
  return {
    score,
    label: labels[score],
    color: colors[score],
    feedback
  };
}
function createPasswordStrengthIndicator(container, password) {
  const strength = evaluatePasswordStrength(password);
  const wrapper = container.createDiv({ cls: "password-strength-wrapper" });
  const bar = wrapper.createDiv({ cls: "password-strength-bar" });
  for (let i = 0; i < 4; i++) {
    const segment = bar.createDiv({ cls: "password-strength-segment" });
    if (i < strength.score) {
      segment.style.backgroundColor = strength.color;
    }
  }
  const label = wrapper.createDiv({ cls: "password-strength-label" });
  label.textContent = `\u5BC6\u7801\u5F3A\u5EA6: ${strength.label}`;
  label.style.color = strength.color;
  if (strength.feedback.length > 0 && password.length > 0) {
    const feedbackEl = wrapper.createDiv({ cls: "password-strength-feedback" });
    feedbackEl.textContent = strength.feedback.join(" \u2022 ");
  }
  return wrapper;
}
var SetupPasswordModal = class extends import_obsidian2.Modal {
  constructor(app, provider, onSuccess) {
    super(app);
    this.provider = provider;
    this.onSuccess = onSuccess;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("secret-storage-modal");
    contentEl.createEl("h2", { text: "\u{1F510} \u8BBE\u7F6E\u4E3B\u5BC6\u7801" });
    const warningEl = contentEl.createDiv({ cls: "setting-item-description" });
    warningEl.style.backgroundColor = "var(--background-modifier-error)";
    warningEl.style.padding = "10px";
    warningEl.style.borderRadius = "5px";
    warningEl.style.marginBottom = "15px";
    warningEl.innerHTML = `
			<strong>\u26A0\uFE0F \u91CD\u8981\u63D0\u793A\uFF1A</strong><br>
			<ul style="margin: 5px 0 0 20px; padding: 0;">
				<li>\u4E3B\u5BC6\u7801\u7528\u4E8E\u52A0\u5BC6\u60A8\u7684\u6240\u6709\u5BC6\u94A5</li>
				<li>\u5982\u679C\u5FD8\u8BB0\u5BC6\u7801\uFF0C<strong>\u65E0\u6CD5\u6062\u590D</strong>\u4EFB\u4F55\u5BC6\u94A5</li>
				<li>\u8BF7\u52A1\u5FC5\u5C06\u5BC6\u7801\u4FDD\u5B58\u5728\u5B89\u5168\u7684\u5730\u65B9</li>
			</ul>
		`;
    new import_obsidian2.Setting(contentEl).setName("\u4E3B\u5BC6\u7801").setDesc("\u7528\u4E8E\u52A0\u5BC6\u5BC6\u94A5\u5E93").addText((text) => {
      this.passwordInput = text;
      text.inputEl.type = "password";
      text.setPlaceholder("\u8F93\u5165\u4E3B\u5BC6\u7801...");
      text.inputEl.addEventListener("input", () => {
        this.updateStrengthIndicator();
      });
    });
    this.strengthContainer = contentEl.createDiv();
    new import_obsidian2.Setting(contentEl).setName("\u786E\u8BA4\u5BC6\u7801").setDesc("\u518D\u6B21\u8F93\u5165\u4E3B\u5BC6\u7801").addText((text) => {
      this.confirmInput = text;
      text.inputEl.type = "password";
      text.setPlaceholder("\u786E\u8BA4\u4E3B\u5BC6\u7801...");
    });
    new import_obsidian2.Setting(contentEl).addButton((btn) => btn.setButtonText("\u521B\u5EFA\u5BC6\u94A5\u5E93").setCta().onClick(() => this.handleSetup())).addButton((btn) => btn.setButtonText("\u53D6\u6D88").onClick(() => this.close()));
  }
  updateStrengthIndicator() {
    this.strengthContainer.empty();
    const password = this.passwordInput.getValue();
    if (password.length > 0) {
      createPasswordStrengthIndicator(this.strengthContainer, password);
    }
  }
  async handleSetup() {
    const password = this.passwordInput.getValue();
    const confirm = this.confirmInput.getValue();
    if (!password) {
      new import_obsidian2.Notice("\u26A0\uFE0F \u8BF7\u8F93\u5165\u4E3B\u5BC6\u7801");
      return;
    }
    if (password.length < 12) {
      new import_obsidian2.Notice("\u26A0\uFE0F \u5BC6\u7801\u81F3\u5C11\u9700\u8981 12 \u4E2A\u5B57\u7B26");
      return;
    }
    if (password !== confirm) {
      new import_obsidian2.Notice("\u26A0\uFE0F \u4E24\u6B21\u8F93\u5165\u7684\u5BC6\u7801\u4E0D\u4E00\u81F4");
      return;
    }
    const strength = evaluatePasswordStrength(password);
    if (strength.score < 2) {
      new import_obsidian2.Notice("\u26A0\uFE0F \u5BC6\u7801\u5F3A\u5EA6\u592A\u5F31\uFF0C\u8BF7\u4F7F\u7528\u66F4\u590D\u6742\u7684\u5BC6\u7801");
      return;
    }
    const success = await this.provider.initialize(password);
    if (success) {
      new import_obsidian2.Notice("\u2705 \u5BC6\u94A5\u5E93\u521B\u5EFA\u6210\u529F");
      this.onSuccess();
      this.close();
    } else {
      new import_obsidian2.Notice("\u274C \u5BC6\u94A5\u5E93\u521B\u5EFA\u5931\u8D25");
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var UnlockModal = class extends import_obsidian2.Modal {
  constructor(app, provider, onSuccess, onCancel) {
    super(app);
    this.provider = provider;
    this.onSuccess = onSuccess;
    this.onCancel = onCancel;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("secret-storage-modal");
    contentEl.createEl("h2", { text: "\u{1F513} \u89E3\u9501\u5BC6\u94A5\u5E93" });
    contentEl.createEl("p", {
      text: "\u8BF7\u8F93\u5165\u4E3B\u5BC6\u7801\u4EE5\u8BBF\u95EE\u60A8\u7684\u5BC6\u94A5",
      cls: "setting-item-description"
    });
    new import_obsidian2.Setting(contentEl).setName("\u4E3B\u5BC6\u7801").addText((text) => {
      this.passwordInput = text;
      text.inputEl.type = "password";
      text.setPlaceholder("\u8F93\u5165\u4E3B\u5BC6\u7801...");
      setTimeout(() => text.inputEl.focus(), 10);
      text.inputEl.addEventListener("keypress", (e) => {
        if (e.key === "Enter") {
          this.handleUnlock();
        }
      });
    });
    new import_obsidian2.Setting(contentEl).addButton((btn) => btn.setButtonText("\u89E3\u9501").setCta().onClick(() => this.handleUnlock())).addButton((btn) => btn.setButtonText("\u53D6\u6D88").onClick(() => {
      if (this.onCancel) {
        this.onCancel();
      }
      this.close();
    }));
    contentEl.createEl("p", {
      text: "\u{1F4A1} \u5BC6\u94A5\u5E93\u4F1A\u5728\u4E00\u6BB5\u65F6\u95F4\u4E0D\u6D3B\u52A8\u540E\u81EA\u52A8\u9501\u5B9A",
      cls: "setting-item-description"
    });
  }
  async handleUnlock() {
    const password = this.passwordInput.getValue();
    if (!password) {
      new import_obsidian2.Notice("\u26A0\uFE0F \u8BF7\u8F93\u5165\u4E3B\u5BC6\u7801");
      return;
    }
    const success = await this.provider.unlock(password);
    if (success) {
      new import_obsidian2.Notice("\u2705 \u5BC6\u94A5\u5E93\u5DF2\u89E3\u9501");
      this.onSuccess();
      this.close();
    } else {
      new import_obsidian2.Notice("\u274C \u5BC6\u7801\u9519\u8BEF");
      this.passwordInput.setValue("");
      this.passwordInput.inputEl.focus();
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var ChangePasswordModal = class extends import_obsidian2.Modal {
  constructor(app, provider, onSuccess) {
    super(app);
    this.provider = provider;
    this.onSuccess = onSuccess;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("secret-storage-modal");
    contentEl.createEl("h2", { text: "\u{1F511} \u4FEE\u6539\u4E3B\u5BC6\u7801" });
    new import_obsidian2.Setting(contentEl).setName("\u5F53\u524D\u5BC6\u7801").addText((text) => {
      this.oldPasswordInput = text;
      text.inputEl.type = "password";
      text.setPlaceholder("\u8F93\u5165\u5F53\u524D\u5BC6\u7801...");
    });
    new import_obsidian2.Setting(contentEl).setName("\u65B0\u5BC6\u7801").addText((text) => {
      this.newPasswordInput = text;
      text.inputEl.type = "password";
      text.setPlaceholder("\u8F93\u5165\u65B0\u5BC6\u7801...");
      text.inputEl.addEventListener("input", () => {
        this.updateStrengthIndicator();
      });
    });
    this.strengthContainer = contentEl.createDiv();
    new import_obsidian2.Setting(contentEl).setName("\u786E\u8BA4\u65B0\u5BC6\u7801").addText((text) => {
      this.confirmInput = text;
      text.inputEl.type = "password";
      text.setPlaceholder("\u786E\u8BA4\u65B0\u5BC6\u7801...");
    });
    new import_obsidian2.Setting(contentEl).addButton((btn) => btn.setButtonText("\u4FEE\u6539\u5BC6\u7801").setCta().onClick(() => this.handleChange())).addButton((btn) => btn.setButtonText("\u53D6\u6D88").onClick(() => this.close()));
  }
  updateStrengthIndicator() {
    this.strengthContainer.empty();
    const password = this.newPasswordInput.getValue();
    if (password.length > 0) {
      createPasswordStrengthIndicator(this.strengthContainer, password);
    }
  }
  async handleChange() {
    const oldPassword = this.oldPasswordInput.getValue();
    const newPassword = this.newPasswordInput.getValue();
    const confirm = this.confirmInput.getValue();
    if (!oldPassword || !newPassword) {
      new import_obsidian2.Notice("\u26A0\uFE0F \u8BF7\u586B\u5199\u6240\u6709\u5B57\u6BB5");
      return;
    }
    if (oldPassword === newPassword) {
      new import_obsidian2.Notice("\u26A0\uFE0F \u65B0\u5BC6\u7801\u4E0D\u80FD\u4E0E\u5F53\u524D\u5BC6\u7801\u76F8\u540C");
      return;
    }
    if (newPassword.length < 12) {
      new import_obsidian2.Notice("\u26A0\uFE0F \u65B0\u5BC6\u7801\u81F3\u5C11\u9700\u8981 12 \u4E2A\u5B57\u7B26");
      return;
    }
    if (newPassword !== confirm) {
      new import_obsidian2.Notice("\u26A0\uFE0F \u4E24\u6B21\u8F93\u5165\u7684\u65B0\u5BC6\u7801\u4E0D\u4E00\u81F4");
      return;
    }
    const strength = evaluatePasswordStrength(newPassword);
    if (strength.score < 2) {
      new import_obsidian2.Notice("\u26A0\uFE0F \u65B0\u5BC6\u7801\u5F3A\u5EA6\u592A\u5F31");
      return;
    }
    const submitBtn = this.contentEl.querySelector(".mod-cta");
    const originalText = (submitBtn == null ? void 0 : submitBtn.textContent) || "\u4FEE\u6539\u5BC6\u7801";
    if (submitBtn) {
      submitBtn.textContent = "\u4FEE\u6539\u4E2D...";
      submitBtn.disabled = true;
    }
    try {
      const success = await this.provider.changePassword(oldPassword, newPassword);
      if (success) {
        new import_obsidian2.Notice("\u2705 \u5BC6\u7801\u4FEE\u6539\u6210\u529F\n\n\u26A0\uFE0F \u8BF7\u52A1\u5FC5\u8BB0\u4F4F\u60A8\u7684\u65B0\u5BC6\u7801\uFF01");
        this.onSuccess();
        this.close();
      } else {
        new import_obsidian2.Notice("\u274C \u5F53\u524D\u5BC6\u7801\u9519\u8BEF");
        this.oldPasswordInput.setValue("");
        this.oldPasswordInput.inputEl.focus();
      }
    } finally {
      if (submitBtn) {
        submitBtn.textContent = originalText;
        submitBtn.disabled = false;
      }
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var MigrationModal = class extends import_obsidian2.Modal {
  constructor(app, provider, localSecrets, onComplete) {
    super(app);
    this.provider = provider;
    this.localSecrets = localSecrets;
    this.onComplete = onComplete;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("secret-storage-modal");
    contentEl.createEl("h2", { text: "\u{1F4E6} \u8FC1\u79FB\u5BC6\u94A5" });
    const secretCount = Object.keys(this.localSecrets).length;
    contentEl.createEl("p", {
      text: `\u53D1\u73B0 ${secretCount} \u4E2A\u5B58\u50A8\u5728\u7CFB\u7EDF\u94A5\u5319\u4E32\u4E2D\u7684\u5BC6\u94A5\u3002\u662F\u5426\u5C06\u5B83\u4EEC\u8FC1\u79FB\u5230\u540C\u6B65\u5BC6\u94A5\u5E93\uFF1F`,
      cls: "setting-item-description"
    });
    if (secretCount > 0) {
      const list = contentEl.createEl("ul");
      for (const id of Object.keys(this.localSecrets)) {
        list.createEl("li", { text: id });
      }
    }
    new import_obsidian2.Setting(contentEl).addButton((btn) => btn.setButtonText("\u8FC1\u79FB\u5E76\u5220\u9664\u672C\u5730\u5BC6\u94A5").setCta().onClick(() => this.handleMigrate(true))).addButton((btn) => btn.setButtonText("\u4EC5\u8FC1\u79FB\uFF08\u4FDD\u7559\u672C\u5730\uFF09").onClick(() => this.handleMigrate(false))).addButton((btn) => btn.setButtonText("\u8DF3\u8FC7").onClick(() => {
      this.onComplete();
      this.close();
    }));
  }
  async handleMigrate(deleteLocal) {
    const success = await this.provider.migrateFromLocal(this.localSecrets);
    if (success) {
      if (deleteLocal) {
        for (const id of Object.keys(this.localSecrets)) {
          this.app.secretStorage.setSecret(id, "");
        }
        new import_obsidian2.Notice("\u2705 \u5BC6\u94A5\u5DF2\u8FC1\u79FB\u5E76\u6E05\u9664\u672C\u5730\u526F\u672C");
      } else {
        new import_obsidian2.Notice("\u2705 \u5BC6\u94A5\u5DF2\u8FC1\u79FB\uFF08\u672C\u5730\u526F\u672C\u5DF2\u4FDD\u7559\uFF09");
      }
      this.onComplete();
      this.close();
    } else {
      new import_obsidian2.Notice("\u274C \u8FC1\u79FB\u5931\u8D25");
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var ConflictResolutionModal = class extends import_obsidian2.Modal {
  constructor(app, provider, conflictInfo, onResolved) {
    super(app);
    this.provider = provider;
    this.conflictInfo = conflictInfo;
    this.onResolved = onResolved;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("secret-storage-modal");
    contentEl.addClass("conflict-resolution-modal");
    contentEl.createEl("h2", { text: "\u26A0\uFE0F \u68C0\u6D4B\u5230\u540C\u6B65\u51B2\u7A81" });
    const warningEl = contentEl.createDiv({ cls: "conflict-warning" });
    warningEl.style.backgroundColor = "var(--background-modifier-error)";
    warningEl.style.padding = "12px";
    warningEl.style.borderRadius = "6px";
    warningEl.style.marginBottom = "16px";
    warningEl.innerHTML = `
			<strong>\u5BC6\u94A5\u5E93\u5728\u591A\u4E2A\u8BBE\u5907\u4E0A\u540C\u65F6\u88AB\u4FEE\u6539</strong><br>
			<span style="font-size: 0.9em;">\u8BF7\u9009\u62E9\u8981\u4FDD\u7559\u7684\u7248\u672C\uFF0C\u6216\u5408\u5E76\u4E24\u4E2A\u7248\u672C\u3002</span>
		`;
    const comparisonEl = contentEl.createDiv({ cls: "conflict-comparison" });
    comparisonEl.style.display = "grid";
    comparisonEl.style.gridTemplateColumns = "1fr 1fr";
    comparisonEl.style.gap = "16px";
    comparisonEl.style.marginBottom = "16px";
    const localEl = comparisonEl.createDiv({ cls: "version-local" });
    localEl.style.padding = "12px";
    localEl.style.backgroundColor = "var(--background-secondary)";
    localEl.style.borderRadius = "6px";
    localEl.style.border = "2px solid var(--interactive-accent)";
    localEl.createEl("h4", { text: "\u{1F4F1} \u672C\u5730\u7248\u672C" });
    localEl.createEl("p", {
      text: `\u4FEE\u6539\u65F6\u95F4: ${this.formatDate(this.conflictInfo.localVault.lastModified)}`,
      cls: "setting-item-description"
    });
    localEl.createEl("p", {
      text: `\u8BBE\u5907: ${this.conflictInfo.localVault.deviceId}`,
      cls: "setting-item-description"
    });
    localEl.createEl("p", {
      text: `\u5BC6\u94A5\u6570\u91CF: ${this.conflictInfo.localSecrets.length}`,
      cls: "setting-item-description"
    });
    if (this.conflictInfo.localSecrets.length > 0) {
      const localList = localEl.createEl("ul");
      localList.style.fontSize = "0.85em";
      localList.style.maxHeight = "100px";
      localList.style.overflowY = "auto";
      this.conflictInfo.localSecrets.forEach((id) => {
        localList.createEl("li", { text: id });
      });
    }
    const remoteEl = comparisonEl.createDiv({ cls: "version-remote" });
    remoteEl.style.padding = "12px";
    remoteEl.style.backgroundColor = "var(--background-secondary)";
    remoteEl.style.borderRadius = "6px";
    remoteEl.style.border = "2px solid var(--text-muted)";
    remoteEl.createEl("h4", { text: "\u2601\uFE0F \u8FDC\u7A0B\u7248\u672C" });
    remoteEl.createEl("p", {
      text: `\u4FEE\u6539\u65F6\u95F4: ${this.formatDate(this.conflictInfo.remoteVault.lastModified)}`,
      cls: "setting-item-description"
    });
    remoteEl.createEl("p", {
      text: `\u8BBE\u5907: ${this.conflictInfo.remoteVault.deviceId}`,
      cls: "setting-item-description"
    });
    remoteEl.createEl("p", {
      text: `\u5BC6\u94A5\u6570\u91CF: ${this.conflictInfo.remoteSecrets.length}`,
      cls: "setting-item-description"
    });
    if (this.conflictInfo.remoteSecrets.length > 0) {
      const remoteList = remoteEl.createEl("ul");
      remoteList.style.fontSize = "0.85em";
      remoteList.style.maxHeight = "100px";
      remoteList.style.overflowY = "auto";
      this.conflictInfo.remoteSecrets.forEach((id) => {
        remoteList.createEl("li", { text: id });
      });
    }
    const diffEl = contentEl.createDiv({ cls: "conflict-diff" });
    diffEl.style.marginBottom = "16px";
    diffEl.style.padding = "12px";
    diffEl.style.backgroundColor = "var(--background-secondary-alt)";
    diffEl.style.borderRadius = "6px";
    const { onlyLocal, onlyRemote, both } = this.analyzeDiff();
    diffEl.createEl("h4", { text: "\u{1F4CA} \u5DEE\u5F02\u5206\u6790" });
    if (both.length > 0) {
      diffEl.createEl("p", {
        text: `\u{1F504} \u4E24\u8FB9\u90FD\u6709: ${both.join(", ")}`,
        cls: "setting-item-description"
      });
    }
    if (onlyLocal.length > 0) {
      diffEl.createEl("p", {
        text: `\u{1F4F1} \u4EC5\u672C\u5730: ${onlyLocal.join(", ")}`,
        cls: "setting-item-description"
      });
    }
    if (onlyRemote.length > 0) {
      diffEl.createEl("p", {
        text: `\u2601\uFE0F \u4EC5\u8FDC\u7A0B: ${onlyRemote.join(", ")}`,
        cls: "setting-item-description"
      });
    }
    const buttonContainer = contentEl.createDiv({ cls: "conflict-buttons" });
    buttonContainer.style.display = "flex";
    buttonContainer.style.gap = "8px";
    buttonContainer.style.flexWrap = "wrap";
    new import_obsidian2.Setting(buttonContainer).addButton((btn) => btn.setButtonText("\u4F7F\u7528\u672C\u5730\u7248\u672C").setTooltip("\u4E22\u5F03\u8FDC\u7A0B\u66F4\u6539\uFF0C\u4FDD\u7559\u672C\u5730\u7248\u672C").onClick(() => this.handleResolution("local"))).addButton((btn) => btn.setButtonText("\u4F7F\u7528\u8FDC\u7A0B\u7248\u672C").setTooltip("\u4E22\u5F03\u672C\u5730\u66F4\u6539\uFF0C\u4F7F\u7528\u8FDC\u7A0B\u7248\u672C").onClick(() => this.handleResolution("remote"))).addButton((btn) => btn.setButtonText("\u5408\u5E76\u4E24\u8005").setCta().setTooltip("\u4FDD\u7559\u4E24\u8FB9\u6240\u6709\u5BC6\u94A5\uFF0C\u51B2\u7A81\u65F6\u53D6\u8F83\u65B0\u7248\u672C").onClick(() => this.handleResolution("merge"))).addButton((btn) => btn.setButtonText("\u53D6\u6D88").onClick(() => this.handleResolution("cancel")));
    const mergeHint = contentEl.createEl("p", {
      cls: "setting-item-description"
    });
    mergeHint.style.marginTop = "12px";
    mergeHint.innerHTML = `
			<strong>\u{1F4A1} \u5408\u5E76\u7B56\u7565:</strong> \u4FDD\u7559\u4E24\u8FB9\u6240\u6709\u7684\u5BC6\u94A5\u3002\u5982\u679C\u540C\u4E00\u5BC6\u94A5\u5728\u4E24\u8FB9\u90FD\u5B58\u5728\u4F46\u503C\u4E0D\u540C\uFF0C\u4FDD\u7559\u8F83\u65B0\u7248\u672C\u7684\u503C\u3002
		`;
  }
  formatDate(isoString) {
    const date = new Date(isoString);
    return date.toLocaleString("zh-CN", {
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit"
    });
  }
  analyzeDiff() {
    const localSet = new Set(this.conflictInfo.localSecrets);
    const remoteSet = new Set(this.conflictInfo.remoteSecrets);
    const onlyLocal = this.conflictInfo.localSecrets.filter((id) => !remoteSet.has(id));
    const onlyRemote = this.conflictInfo.remoteSecrets.filter((id) => !localSet.has(id));
    const both = this.conflictInfo.localSecrets.filter((id) => remoteSet.has(id));
    return { onlyLocal, onlyRemote, both };
  }
  async handleResolution(resolution) {
    let success = false;
    switch (resolution) {
      case "local":
        success = await this.provider.resolveConflictWithLocal();
        if (success) {
          new import_obsidian2.Notice("\u2705 \u5DF2\u4F7F\u7528\u672C\u5730\u7248\u672C");
        }
        break;
      case "remote":
        success = await this.provider.resolveConflictWithRemote();
        if (success) {
          new import_obsidian2.Notice("\u2705 \u5DF2\u4F7F\u7528\u8FDC\u7A0B\u7248\u672C");
        }
        break;
      case "merge":
        success = await this.provider.resolveConflictWithMerge();
        if (success) {
          new import_obsidian2.Notice("\u2705 \u5DF2\u5408\u5E76\u4E24\u4E2A\u7248\u672C");
        }
        break;
      case "cancel":
        this.onResolved("cancel");
        this.close();
        return;
    }
    if (success) {
      this.onResolved(resolution);
      this.close();
    } else {
      new import_obsidian2.Notice("\u274C \u89E3\u51B3\u51B2\u7A81\u5931\u8D25");
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  showNotifications: true,
  enablePlaceholderReplacement: true,
  placeholderStyle: "blur",
  // 同步模式默认设置
  storageMode: "local",
  autoLockTimeout: 30,
  keepBackupCount: 5
};
var SECRET_PLACEHOLDER_REGEX = /\{\{secret:([a-z0-9-]+)\}\}/g;
var SecretStorageDemoPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    await this.initStorageProvider();
    this.registerMarkdownPostProcessor((element, context) => {
      this.processSecretPlaceholders(element, context);
    });
    this.addCommand({
      id: "insert-secret-placeholder",
      name: "\u63D2\u5165\u5BC6\u94A5\u5360\u4F4D\u7B26 (Insert Secret Placeholder)",
      editorCallback: (editor, view) => {
        this.ensureUnlocked(() => {
          new InsertPlaceholderModal(this.app, this, editor).open();
        });
      }
    });
    this.addCommand({
      id: "replace-selection-with-secret",
      name: "\u5C06\u9009\u4E2D\u6587\u672C\u4FDD\u5B58\u4E3A\u5BC6\u94A5\u5E76\u66FF\u6362 (Save Selection as Secret)",
      editorCallback: (editor, view) => {
        const selection = editor.getSelection();
        if (!selection || selection.trim() === "") {
          new import_obsidian3.Notice("\u26A0\uFE0F \u8BF7\u5148\u9009\u4E2D\u8981\u4FDD\u5B58\u4E3A\u5BC6\u94A5\u7684\u6587\u672C");
          return;
        }
        this.ensureUnlocked(() => {
          new ReplaceWithSecretModal(this.app, this, editor, selection).open();
        });
      }
    });
    this.addCommand({
      id: "save-secret",
      name: "\u4FDD\u5B58\u5BC6\u94A5 (Save Secret)",
      callback: () => {
        this.ensureUnlocked(() => {
          new SaveSecretModal(this.app, this).open();
        });
      }
    });
    this.addCommand({
      id: "get-secret",
      name: "\u83B7\u53D6\u5BC6\u94A5 (Get Secret)",
      callback: () => {
        this.ensureUnlocked(() => {
          new GetSecretModal(this.app, this).open();
        });
      }
    });
    this.addCommand({
      id: "list-secrets",
      name: "\u5217\u51FA\u6240\u6709\u5BC6\u94A5 (List All Secrets)",
      callback: () => {
        this.ensureUnlocked(() => {
          this.listAllSecrets();
        });
      }
    });
    this.addCommand({
      id: "delete-secret",
      name: "\u5220\u9664\u5BC6\u94A5 (Delete Secret)",
      callback: () => {
        this.ensureUnlocked(() => {
          new DeleteSecretModal(this.app, this).open();
        });
      }
    });
    this.addCommand({
      id: "unlock-vault",
      name: "\u89E3\u9501\u5BC6\u94A5\u5E93 (Unlock Vault)",
      checkCallback: (checking) => {
        if (this.settings.storageMode === "sync") {
          if (!checking) {
            this.ensureUnlocked(() => {
              new import_obsidian3.Notice("\u2705 \u5BC6\u94A5\u5E93\u5DF2\u89E3\u9501");
            });
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "lock-vault",
      name: "\u9501\u5B9A\u5BC6\u94A5\u5E93 (Lock Vault)",
      checkCallback: (checking) => {
        if (this.settings.storageMode === "sync" && this.storageProvider.isUnlocked()) {
          if (!checking) {
            this.storageProvider.lock();
            new import_obsidian3.Notice("\u{1F512} \u5BC6\u94A5\u5E93\u5DF2\u9501\u5B9A");
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "change-password",
      name: "\u4FEE\u6539\u4E3B\u5BC6\u7801 (Change Master Password)",
      checkCallback: (checking) => {
        if (this.settings.storageMode !== "sync")
          return false;
        if (!this.storageProvider.isUnlocked())
          return false;
        if (!checking) {
          new ChangePasswordModal(
            this.app,
            this.storageProvider,
            () => new import_obsidian3.Notice("\u2705 \u5BC6\u7801\u5DF2\u4FEE\u6539")
          ).open();
        }
        return true;
      }
    });
    this.addCommand({
      id: "check-sync",
      name: "\u68C0\u67E5\u540C\u6B65\u72B6\u6001 (Check Sync Status)",
      checkCallback: (checking) => {
        if (this.settings.storageMode === "sync" && this.storageProvider.isUnlocked()) {
          if (!checking) {
            this.checkSyncStatus();
          }
          return true;
        }
        return false;
      }
    });
    this.addSettingTab(new SecretStorageSettingTab(this.app, this));
    this.addRibbonIcon("key", "Secret Storage", () => {
      this.ensureUnlocked(() => {
        new SecretManagerModal(this.app, this).open();
      });
    });
    console.log("SecretStorage Demo Plugin loaded");
  }
  onunload() {
    if (this.settings.storageMode === "sync" && this.storageProvider) {
      this.storageProvider.lock();
    }
    console.log("SecretStorage Demo Plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // ============================================
  // 存储提供者管理
  // ============================================
  /**
   * 初始化存储提供者
   */
  async initStorageProvider() {
    this.storageProvider = createStorageProvider(
      this.app,
      this.settings.storageMode,
      this.settings.autoLockTimeout
    );
  }
  /**
   * 切换存储模式
   */
  async switchStorageMode(newMode) {
    if (newMode === this.settings.storageMode) {
      return;
    }
    if (newMode === "sync") {
      const syncProvider = new SyncStorageProvider(this.app, this.settings.autoLockTimeout);
      const isInitialized = await syncProvider.isInitialized();
      if (!isInitialized) {
        new SetupPasswordModal(this.app, syncProvider, async () => {
          const localSecrets = await this.getLocalSecretsMap();
          if (Object.keys(localSecrets).length > 0) {
            new MigrationModal(this.app, syncProvider, localSecrets, () => {
              this.storageProvider = syncProvider;
              this.settings.storageMode = "sync";
              this.saveSettings();
              new import_obsidian3.Notice("\u2705 \u5DF2\u5207\u6362\u5230\u540C\u6B65\u6A21\u5F0F");
            }).open();
          } else {
            this.storageProvider = syncProvider;
            this.settings.storageMode = "sync";
            this.saveSettings();
            new import_obsidian3.Notice("\u2705 \u5DF2\u5207\u6362\u5230\u540C\u6B65\u6A21\u5F0F");
          }
        }).open();
      } else {
        new UnlockModal(this.app, syncProvider, async () => {
          this.storageProvider = syncProvider;
          this.settings.storageMode = "sync";
          this.saveSettings();
          new import_obsidian3.Notice("\u2705 \u5DF2\u5207\u6362\u5230\u540C\u6B65\u6A21\u5F0F");
        }).open();
      }
    } else {
      this.storageProvider = new LocalStorageProvider(this.app);
      this.settings.storageMode = "local";
      await this.saveSettings();
      new import_obsidian3.Notice("\u2705 \u5DF2\u5207\u6362\u5230\u672C\u5730\u6A21\u5F0F");
    }
  }
  /**
   * 获取本地密钥映射
   */
  async getLocalSecretsMap() {
    const localProvider = new LocalStorageProvider(this.app);
    const ids = await localProvider.list();
    const secrets = {};
    for (const id of ids) {
      const secret = await localProvider.get(id);
      if (secret) {
        secrets[id] = secret;
      }
    }
    return secrets;
  }
  /**
   * 确保密钥库已解锁
   */
  ensureUnlocked(callback) {
    if (this.settings.storageMode === "local") {
      callback();
      return;
    }
    const syncProvider = this.storageProvider;
    if (syncProvider.isUnlocked()) {
      this.checkAndHandleConflict(syncProvider, callback);
      return;
    }
    syncProvider.isInitialized().then((initialized) => {
      if (!initialized) {
        new SetupPasswordModal(this.app, syncProvider, callback).open();
      } else {
        new UnlockModal(this.app, syncProvider, () => {
          this.checkAndHandleConflict(syncProvider, callback);
        }).open();
      }
    });
  }
  /**
   * 检查并处理同步冲突
   */
  async checkAndHandleConflict(syncProvider, callback) {
    const conflictType = await syncProvider.detectConflict();
    switch (conflictType) {
      case "none":
      case "local-newer":
        callback();
        break;
      case "remote-newer":
        await syncProvider.refresh();
        new import_obsidian3.Notice("\u{1F504} \u5DF2\u540C\u6B65\u8FDC\u7A0B\u66F4\u65B0");
        callback();
        break;
      case "conflict":
        const conflictInfo = syncProvider.getConflictInfo();
        if (conflictInfo) {
          new ConflictResolutionModal(
            this.app,
            syncProvider,
            conflictInfo,
            (resolution) => {
              if (resolution !== "cancel") {
                callback();
              }
            }
          ).open();
        } else {
          callback();
        }
        break;
    }
  }
  /**
   * 检查同步状态
   */
  async checkSyncStatus() {
    if (this.settings.storageMode !== "sync") {
      new import_obsidian3.Notice("\u26A0\uFE0F \u4EC5\u540C\u6B65\u6A21\u5F0F\u53EF\u7528");
      return;
    }
    const syncProvider = this.storageProvider;
    if (!syncProvider.isUnlocked()) {
      new import_obsidian3.Notice("\u26A0\uFE0F \u8BF7\u5148\u89E3\u9501\u5BC6\u94A5\u5E93");
      return;
    }
    const conflictType = await syncProvider.detectConflict();
    switch (conflictType) {
      case "none":
        new import_obsidian3.Notice("\u2705 \u540C\u6B65\u72B6\u6001\u6B63\u5E38\uFF0C\u65E0\u51B2\u7A81");
        break;
      case "local-newer":
        new import_obsidian3.Notice("\u{1F4F1} \u672C\u5730\u7248\u672C\u8F83\u65B0\uFF0C\u7B49\u5F85\u540C\u6B65\u4E0A\u4F20");
        break;
      case "remote-newer":
        await syncProvider.refresh();
        new import_obsidian3.Notice("\u{1F504} \u5DF2\u540C\u6B65\u8FDC\u7A0B\u66F4\u65B0");
        break;
      case "conflict":
        const conflictInfo = syncProvider.getConflictInfo();
        if (conflictInfo) {
          new ConflictResolutionModal(
            this.app,
            syncProvider,
            conflictInfo,
            (resolution) => {
              if (resolution !== "cancel") {
                new import_obsidian3.Notice(`\u2705 \u51B2\u7A81\u5DF2\u89E3\u51B3 (${resolution})`);
              }
            }
          ).open();
        } else {
          new import_obsidian3.Notice("\u26A0\uFE0F \u68C0\u6D4B\u5230\u51B2\u7A81\u4F46\u65E0\u6CD5\u83B7\u53D6\u8BE6\u60C5");
        }
        break;
    }
  }
  // ============================================
  // SecretStorage API 核心方法
  // ============================================
  /**
   * 保存密钥
   */
  async saveSecret(id, secret) {
    if (!/^[a-z0-9-]+$/.test(id)) {
      new import_obsidian3.Notice("\u274C \u5BC6\u94A5ID\u53EA\u80FD\u5305\u542B\u5C0F\u5199\u5B57\u6BCD\u3001\u6570\u5B57\u548C\u77ED\u6A2A\u7EBF");
      return false;
    }
    const success = await this.storageProvider.save(id, secret);
    if (success && this.settings.showNotifications) {
      const modeText = this.settings.storageMode === "sync" ? "\u540C\u6B65\u5BC6\u94A5\u5E93" : "\u7CFB\u7EDF\u94A5\u5319\u4E32";
      new import_obsidian3.Notice(`\u2705 \u5BC6\u94A5 "${id}" \u5DF2\u4FDD\u5B58\u5230${modeText}`);
    }
    return success;
  }
  /**
   * 获取密钥
   */
  async getSecret(id) {
    return this.storageProvider.get(id);
  }
  /**
   * 列出所有密钥 ID
   */
  async listSecrets() {
    return this.storageProvider.list();
  }
  /**
   * 删除密钥
   */
  async deleteSecret(id) {
    const success = await this.storageProvider.delete(id);
    if (success && this.settings.showNotifications) {
      new import_obsidian3.Notice(`\u{1F5D1}\uFE0F \u5BC6\u94A5 "${id}" \u5DF2\u5220\u9664`);
    }
    return success;
  }
  /**
   * 列出并显示所有密钥
   */
  async listAllSecrets() {
    const secrets = await this.listSecrets();
    if (secrets.length === 0) {
      new import_obsidian3.Notice("\u{1F4ED} \u6CA1\u6709\u5B58\u50A8\u7684\u5BC6\u94A5");
    } else {
      new import_obsidian3.Notice(`\u{1F511} \u5DF2\u5B58\u50A8\u7684\u5BC6\u94A5 (${secrets.length}\u4E2A):
${secrets.join("\n")}`);
    }
  }
  // ============================================
  // 占位符处理功能
  // ============================================
  /**
   * 处理 Markdown 中的密钥占位符
   */
  processSecretPlaceholders(element, context) {
    if (!this.settings.enablePlaceholderReplacement)
      return;
    const isUnlocked = this.storageProvider.isUnlocked();
    const walker = document.createTreeWalker(
      element,
      NodeFilter.SHOW_TEXT,
      null
    );
    const nodesToReplace = [];
    let node;
    while (node = walker.nextNode()) {
      const text = node.textContent || "";
      const matches = [...text.matchAll(SECRET_PLACEHOLDER_REGEX)];
      if (matches.length > 0) {
        nodesToReplace.push({ node, matches });
      }
    }
    for (const { node: node2, matches } of nodesToReplace) {
      const parent = node2.parentNode;
      if (!parent)
        continue;
      let lastIndex = 0;
      const fragment = document.createDocumentFragment();
      const text = node2.textContent || "";
      for (const match of matches) {
        const secretId = match[1];
        const matchIndex = match.index;
        if (matchIndex > lastIndex) {
          fragment.appendChild(document.createTextNode(text.slice(lastIndex, matchIndex)));
        }
        const secretEl = this.createSecretElement(secretId, isUnlocked);
        fragment.appendChild(secretEl);
        lastIndex = matchIndex + match[0].length;
      }
      if (lastIndex < text.length) {
        fragment.appendChild(document.createTextNode(text.slice(lastIndex)));
      }
      parent.replaceChild(fragment, node2);
    }
  }
  /**
   * 创建密钥显示元素
   */
  createSecretElement(secretId, isUnlocked = true) {
    const container = document.createElement("span");
    container.addClass("secret-placeholder");
    if (!isUnlocked) {
      container.addClass("secret-locked");
      const idLength = secretId.length;
      let displayText;
      let titleText;
      if (idLength <= 3) {
        displayText = "\u{1F512}";
        titleText = `\u5BC6\u94A5 "${secretId}" - \u70B9\u51FB\u89E3\u9501`;
      } else if (idLength <= 6) {
        displayText = `\u{1F512} ${secretId}`;
        titleText = "\u70B9\u51FB\u89E3\u9501\u5BC6\u94A5\u5E93";
      } else if (idLength <= 12) {
        displayText = "\u{1F512} \u70B9\u51FB\u89E3\u9501";
        titleText = `\u5BC6\u94A5 "${secretId}" - \u70B9\u51FB\u89E3\u9501\u5BC6\u94A5\u5E93`;
      } else {
        displayText = "\u{1F512} \u70B9\u51FB\u89E3\u9501\u4EE5\u67E5\u770B\u5BC6\u94A5";
        titleText = `\u5BC6\u94A5 "${secretId}"`;
      }
      container.textContent = displayText;
      container.title = titleText;
      container.style.cursor = "pointer";
      container.addEventListener("click", () => {
        this.ensureUnlocked(() => {
          const activeView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
          if (activeView) {
            activeView.previewMode.rerender(true);
          }
        });
      });
      return container;
    }
    this.getSecret(secretId).then((secret) => {
      if (!secret) {
        container.addClass("secret-not-found");
        container.textContent = `\u26A0\uFE0F {{secret:${secretId}}}`;
        container.title = `\u5BC6\u94A5 "${secretId}" \u672A\u627E\u5230`;
        return;
      }
      switch (this.settings.placeholderStyle) {
        case "blur":
          container.addClass("secret-blur");
          container.textContent = secret;
          container.title = `\u60AC\u505C\u67E5\u770B | \u70B9\u51FB\u590D\u5236\u5BC6\u94A5 "${secretId}"`;
          break;
        case "hidden":
          container.addClass("secret-hidden");
          container.textContent = "\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022";
          container.title = `\u70B9\u51FB\u590D\u5236\u5BC6\u94A5 "${secretId}"`;
          break;
        case "plain":
          container.textContent = secret;
          container.title = `\u70B9\u51FB\u590D\u5236\u5BC6\u94A5 "${secretId}"`;
          break;
      }
      container.style.cursor = "pointer";
      container.addEventListener("click", async () => {
        await navigator.clipboard.writeText(secret);
        new import_obsidian3.Notice(`\u2705 \u5BC6\u94A5 "${secretId}" \u5DF2\u590D\u5236\u5230\u526A\u8D34\u677F`);
      });
    });
    container.textContent = "...";
    return container;
  }
};
var InsertPlaceholderModal = class extends import_obsidian3.Modal {
  constructor(app, plugin, editor) {
    super(app);
    this.plugin = plugin;
    this.editor = editor;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u{1F4DD} \u63D2\u5165\u5BC6\u94A5\u5360\u4F4D\u7B26" });
    contentEl.createEl("p", {
      text: "\u9009\u62E9\u4E00\u4E2A\u5DF2\u4FDD\u5B58\u7684\u5BC6\u94A5\uFF0C\u63D2\u5165\u5360\u4F4D\u7B26\u5230\u5F53\u524D\u5149\u6807\u4F4D\u7F6E",
      cls: "setting-item-description"
    });
    const secrets = await this.plugin.listSecrets();
    if (secrets.length === 0) {
      contentEl.createEl("p", { text: "\u274C \u6CA1\u6709\u5DF2\u5B58\u50A8\u7684\u5BC6\u94A5\uFF0C\u8BF7\u5148\u4FDD\u5B58\u5BC6\u94A5" });
      new import_obsidian3.Setting(contentEl).addButton((btn) => btn.setButtonText("\u4FDD\u5B58\u5BC6\u94A5").setCta().onClick(() => {
        this.close();
        new SaveSecretModal(this.app, this.plugin).open();
      }));
      return;
    }
    contentEl.createEl("p", {
      text: "\u5360\u4F4D\u7B26\u8BED\u6CD5: {{secret:\u5BC6\u94A5ID}}",
      cls: "setting-item-description"
    });
    secrets.forEach((id) => {
      new import_obsidian3.Setting(contentEl).setName(id).setDesc(`\u63D2\u5165 {{secret:${id}}}`).addButton((btn) => btn.setButtonText("\u63D2\u5165").setCta().onClick(() => {
        const placeholder = `{{secret:${id}}}`;
        this.editor.replaceSelection(placeholder);
        this.close();
        new import_obsidian3.Notice(`\u2705 \u5DF2\u63D2\u5165\u5360\u4F4D\u7B26: ${placeholder}`);
      }));
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var ReplaceWithSecretModal = class extends import_obsidian3.Modal {
  constructor(app, plugin, editor, selectedText) {
    super(app);
    this.plugin = plugin;
    this.editor = editor;
    this.selectedText = selectedText;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u{1F510} \u4FDD\u5B58\u5E76\u66FF\u6362\u4E3A\u5360\u4F4D\u7B26" });
    const maskedText = this.selectedText.length > 8 ? this.selectedText.slice(0, 4) + "\u2022\u2022\u2022\u2022" + this.selectedText.slice(-4) : "\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022";
    contentEl.createEl("p", {
      text: `\u9009\u4E2D\u7684\u5BC6\u94A5: ${maskedText}`,
      cls: "setting-item-description"
    });
    contentEl.createEl("p", {
      text: `\u957F\u5EA6: ${this.selectedText.length} \u5B57\u7B26`,
      cls: "setting-item-description"
    });
    new import_obsidian3.Setting(contentEl).setName("\u5BC6\u94A5 ID").setDesc("\u53EA\u80FD\u5305\u542B\u5C0F\u5199\u5B57\u6BCD\u3001\u6570\u5B57\u548C\u77ED\u6A2A\u7EBF").addText((text) => {
      this.idInput = text;
      text.setPlaceholder("my-api-key");
      setTimeout(() => text.inputEl.focus(), 10);
    });
    new import_obsidian3.Setting(contentEl).addButton((btn) => btn.setButtonText("\u4FDD\u5B58\u5E76\u66FF\u6362").setCta().onClick(async () => {
      const id = this.idInput.getValue().trim().toLowerCase();
      if (!id) {
        new import_obsidian3.Notice("\u26A0\uFE0F \u8BF7\u8F93\u5165\u5BC6\u94A5 ID");
        return;
      }
      if (!/^[a-z0-9-]+$/.test(id)) {
        new import_obsidian3.Notice("\u274C \u5BC6\u94A5ID\u53EA\u80FD\u5305\u542B\u5C0F\u5199\u5B57\u6BCD\u3001\u6570\u5B57\u548C\u77ED\u6A2A\u7EBF");
        return;
      }
      if (await this.plugin.saveSecret(id, this.selectedText)) {
        const placeholder = `{{secret:${id}}}`;
        this.editor.replaceSelection(placeholder);
        this.close();
        new import_obsidian3.Notice(`\u2705 \u5DF2\u4FDD\u5B58\u5BC6\u94A5\u5E76\u66FF\u6362\u4E3A: ${placeholder}`);
      }
    })).addButton((btn) => btn.setButtonText("\u53D6\u6D88").onClick(() => this.close()));
    contentEl.createEl("hr");
    const tipEl = contentEl.createEl("div", { cls: "setting-item-description" });
    tipEl.innerHTML = `
			<p>\u{1F4A1} <strong>\u64CD\u4F5C\u8BF4\u660E:</strong></p>
			<ol>
				<li>\u8F93\u5165\u4E00\u4E2A\u6613\u8BB0\u7684\u5BC6\u94A5 ID</li>
				<li>\u70B9\u51FB"\u4FDD\u5B58\u5E76\u66FF\u6362"</li>
				<li>\u9009\u4E2D\u7684\u6587\u672C\u5C06\u4FDD\u5B58\u5230\u5BC6\u94A5\u5E93</li>
				<li>\u539F\u6587\u672C\u66FF\u6362\u4E3A <code>{{secret:\u5BC6\u94A5ID}}</code></li>
			</ol>
		`;
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var SaveSecretModal = class extends import_obsidian3.Modal {
  constructor(app, plugin, onSaveSuccess) {
    super(app);
    this.plugin = plugin;
    this.onSaveSuccess = onSaveSuccess;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u{1F510} \u4FDD\u5B58\u5BC6\u94A5" });
    new import_obsidian3.Setting(contentEl).setName("\u5BC6\u94A5 ID").setDesc("\u53EA\u80FD\u5305\u542B\u5C0F\u5199\u5B57\u6BCD\u3001\u6570\u5B57\u548C\u77ED\u6A2A\u7EBF (\u4F8B\u5982: my-api-key)").addText((text) => {
      this.idInput = text;
      text.setPlaceholder("my-api-key");
    });
    new import_obsidian3.Setting(contentEl).setName("\u5BC6\u94A5\u503C").setDesc("\u5C06\u5B89\u5168\u5B58\u50A8\u5728\u5BC6\u94A5\u5E93\u4E2D").addText((text) => {
      this.secretInput = text;
      text.setPlaceholder("your-secret-value");
      text.inputEl.type = "password";
    });
    new import_obsidian3.Setting(contentEl).addButton((btn) => btn.setButtonText("\u4FDD\u5B58").setCta().onClick(async () => {
      var _a;
      const id = this.idInput.getValue().trim();
      const secret = this.secretInput.getValue();
      if (!id || !secret) {
        new import_obsidian3.Notice("\u8BF7\u586B\u5199\u6240\u6709\u5B57\u6BB5");
        return;
      }
      if (await this.plugin.saveSecret(id, secret)) {
        this.close();
        (_a = this.onSaveSuccess) == null ? void 0 : _a.call(this);
      }
    })).addButton((btn) => btn.setButtonText("\u53D6\u6D88").onClick(() => this.close()));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var GetSecretModal = class extends import_obsidian3.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u{1F50D} \u83B7\u53D6\u5BC6\u94A5" });
    const secrets = await this.plugin.listSecrets();
    if (secrets.length === 0) {
      contentEl.createEl("p", { text: "\u6CA1\u6709\u5DF2\u5B58\u50A8\u7684\u5BC6\u94A5" });
      return;
    }
    for (const id of secrets) {
      new import_obsidian3.Setting(contentEl).setName(id).addButton((btn) => btn.setButtonText("\u67E5\u770B").onClick(async () => {
        const secret = await this.plugin.getSecret(id);
        if (secret) {
          new import_obsidian3.Notice(`\u5BC6\u94A5 "${id}":
${secret}`, 5e3);
        } else {
          new import_obsidian3.Notice(`\u5BC6\u94A5 "${id}" \u4E0D\u5B58\u5728\u6216\u4E3A\u7A7A`);
        }
      })).addButton((btn) => btn.setButtonText("\u590D\u5236").onClick(async () => {
        const secret = await this.plugin.getSecret(id);
        if (secret) {
          await navigator.clipboard.writeText(secret);
          new import_obsidian3.Notice(`\u2705 \u5BC6\u94A5 "${id}" \u5DF2\u590D\u5236\u5230\u526A\u8D34\u677F`);
        }
      }));
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var DeleteSecretModal = class extends import_obsidian3.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u{1F5D1}\uFE0F \u5220\u9664\u5BC6\u94A5" });
    const secrets = await this.plugin.listSecrets();
    if (secrets.length === 0) {
      contentEl.createEl("p", { text: "\u6CA1\u6709\u5DF2\u5B58\u50A8\u7684\u5BC6\u94A5" });
      return;
    }
    for (const id of secrets) {
      new import_obsidian3.Setting(contentEl).setName(id).addButton((btn) => btn.setButtonText("\u5220\u9664").setWarning().onClick(async () => {
        if (await this.plugin.deleteSecret(id)) {
          this.close();
          new DeleteSecretModal(this.app, this.plugin).open();
        }
      }));
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var SecretManagerModal = class extends import_obsidian3.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("secret-manager-modal");
    contentEl.createEl("h2", { text: "\u{1F510} \u5BC6\u94A5\u7BA1\u7406\u5668" });
    const modeText = this.plugin.settings.storageMode === "sync" ? "\u540C\u6B65\u6A21\u5F0F (\u52A0\u5BC6\u6587\u4EF6)" : "\u672C\u5730\u6A21\u5F0F (\u7CFB\u7EDF\u94A5\u5319\u4E32)";
    const lockStatus = this.plugin.storageProvider.isUnlocked() ? "\u{1F513} \u5DF2\u89E3\u9501" : "\u{1F512} \u5DF2\u9501\u5B9A";
    contentEl.createEl("p", {
      text: `\u6A21\u5F0F: ${modeText} | \u72B6\u6001: ${lockStatus}`,
      cls: "setting-item-description"
    });
    if (this.plugin.settings.storageMode === "sync") {
      const syncProvider = this.plugin.storageProvider;
      new import_obsidian3.Setting(contentEl).setName("\u9501\u5B9A\u5BC6\u94A5\u5E93").setDesc("\u7ACB\u5373\u9501\u5B9A\uFF0C\u9700\u8981\u91CD\u65B0\u8F93\u5165\u5BC6\u7801\u624D\u80FD\u8BBF\u95EE").addButton((btn) => btn.setButtonText("\u9501\u5B9A").onClick(() => {
        syncProvider.lock();
        this.close();
        new import_obsidian3.Notice("\u{1F512} \u5BC6\u94A5\u5E93\u5DF2\u9501\u5B9A");
      }));
      new import_obsidian3.Setting(contentEl).setName("\u4FEE\u6539\u4E3B\u5BC6\u7801").setDesc("\u66F4\u6539\u7528\u4E8E\u52A0\u5BC6\u5BC6\u94A5\u5E93\u7684\u5BC6\u7801").addButton((btn) => btn.setButtonText("\u4FEE\u6539\u5BC6\u7801").onClick(() => {
        this.close();
        new ChangePasswordModal(this.app, syncProvider, () => {
          new import_obsidian3.Notice("\u2705 \u5BC6\u7801\u5DF2\u4FEE\u6539");
        }).open();
      }));
      contentEl.createEl("hr");
    }
    new import_obsidian3.Setting(contentEl).setName("\u4FDD\u5B58\u65B0\u5BC6\u94A5").setDesc("\u5C06\u5BC6\u94A5\u5B89\u5168\u5B58\u50A8\u5230\u5BC6\u94A5\u5E93").addButton((btn) => btn.setButtonText("\u4FDD\u5B58\u5BC6\u94A5").setCta().onClick(() => {
      this.close();
      new SaveSecretModal(this.app, this.plugin).open();
    }));
    new import_obsidian3.Setting(contentEl).setName("\u67E5\u770B/\u590D\u5236\u5BC6\u94A5").setDesc("\u67E5\u770B\u6216\u590D\u5236\u5DF2\u5B58\u50A8\u7684\u5BC6\u94A5").addButton((btn) => btn.setButtonText("\u67E5\u770B\u5BC6\u94A5").onClick(() => {
      this.close();
      new GetSecretModal(this.app, this.plugin).open();
    }));
    new import_obsidian3.Setting(contentEl).setName("\u5220\u9664\u5BC6\u94A5").setDesc("\u4ECE\u5BC6\u94A5\u5E93\u4E2D\u5220\u9664\u5BC6\u94A5").addButton((btn) => btn.setButtonText("\u5220\u9664\u5BC6\u94A5").setWarning().onClick(() => {
      this.close();
      new DeleteSecretModal(this.app, this.plugin).open();
    }));
    const secrets = await this.plugin.listSecrets();
    contentEl.createEl("hr");
    contentEl.createEl("p", {
      text: `\u{1F4CA} \u5F53\u524D\u5DF2\u5B58\u50A8 ${secrets.length} \u4E2A\u5BC6\u94A5`,
      cls: "setting-item-description"
    });
    if (secrets.length > 0) {
      const list = contentEl.createEl("ul");
      secrets.forEach((id) => {
        list.createEl("li", { text: id });
      });
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var SecretStorageSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    // 密钥管理区块引用，用于局部刷新
    this.secretSectionEl = null;
    // 当前正在编辑的密钥 ID
    this.editingId = null;
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "SecretStorage \u63D2\u4EF6\u8BBE\u7F6E" });
    containerEl.createEl("h3", { text: "\u5B58\u50A8\u6A21\u5F0F" });
    new import_obsidian3.Setting(containerEl).setName("\u5B58\u50A8\u6A21\u5F0F").setDesc("\u9009\u62E9\u5BC6\u94A5\u5B58\u50A8\u65B9\u5F0F").addDropdown((dropdown) => dropdown.addOption("local", "\u672C\u5730\u6A21\u5F0F (\u7CFB\u7EDF\u94A5\u5319\u4E32\uFF0C\u4E0D\u53EF\u540C\u6B65)").addOption("sync", "\u540C\u6B65\u6A21\u5F0F (\u52A0\u5BC6\u6587\u4EF6\uFF0C\u53EF\u540C\u6B65)").setValue(this.plugin.settings.storageMode).onChange(async (value) => {
      await this.plugin.switchStorageMode(value);
      this.display();
    }));
    if (this.plugin.settings.storageMode === "sync") {
      new import_obsidian3.Setting(containerEl).setName("\u81EA\u52A8\u9501\u5B9A\u65F6\u95F4").setDesc("\u4E0D\u6D3B\u52A8\u591A\u4E45\u540E\u81EA\u52A8\u9501\u5B9A\u5BC6\u94A5\u5E93\uFF08\u5206\u949F\uFF0C0 \u8868\u793A\u7981\u7528\uFF09").addSlider((slider) => slider.setLimits(0, 120, 5).setValue(this.plugin.settings.autoLockTimeout).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.autoLockTimeout = value;
        await this.plugin.saveSettings();
        if (this.plugin.storageProvider.getMode() === "sync") {
          this.plugin.storageProvider.setAutoLockTimeout(value);
        }
      }));
      new import_obsidian3.Setting(containerEl).setName("\u5907\u4EFD\u6570\u91CF").setDesc("\u4FDD\u7559\u591A\u5C11\u4E2A\u5386\u53F2\u5907\u4EFD\u7248\u672C").addSlider((slider) => slider.setLimits(0, 20, 1).setValue(this.plugin.settings.keepBackupCount).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.keepBackupCount = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian3.Setting(containerEl).setName("\u4FEE\u6539\u4E3B\u5BC6\u7801").setDesc("\u66F4\u6539\u5BC6\u94A5\u5E93\u7684\u4E3B\u5BC6\u7801\uFF08\u9700\u8981\u5148\u89E3\u9501\uFF09").addButton((btn) => btn.setButtonText("\u4FEE\u6539\u5BC6\u7801").onClick(() => {
        if (!this.plugin.storageProvider.isUnlocked()) {
          new import_obsidian3.Notice("\u26A0\uFE0F \u8BF7\u5148\u89E3\u9501\u5BC6\u94A5\u5E93");
          return;
        }
        new ChangePasswordModal(
          this.app,
          this.plugin.storageProvider,
          () => new import_obsidian3.Notice("\u2705 \u5BC6\u7801\u5DF2\u4FEE\u6539")
        ).open();
      }));
    }
    containerEl.createEl("h3", { text: "\u901A\u7528\u8BBE\u7F6E" });
    new import_obsidian3.Setting(containerEl).setName("\u663E\u793A\u901A\u77E5").setDesc("\u64CD\u4F5C\u5B8C\u6210\u540E\u663E\u793A\u901A\u77E5\u6D88\u606F").addToggle((toggle) => toggle.setValue(this.plugin.settings.showNotifications).onChange(async (value) => {
      this.plugin.settings.showNotifications = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "\u5360\u4F4D\u7B26\u8BBE\u7F6E" });
    new import_obsidian3.Setting(containerEl).setName("\u542F\u7528\u5360\u4F4D\u7B26\u66FF\u6362").setDesc("\u5728\u9605\u8BFB\u6A21\u5F0F\u4E0B\u81EA\u52A8\u5C06 {{secret:\u5BC6\u94A5ID}} \u66FF\u6362\u4E3A\u771F\u5B9E\u5BC6\u94A5\u503C").addToggle((toggle) => toggle.setValue(this.plugin.settings.enablePlaceholderReplacement).onChange(async (value) => {
      this.plugin.settings.enablePlaceholderReplacement = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u5BC6\u94A5\u663E\u793A\u6837\u5F0F").setDesc("\u5728\u9605\u8BFB\u6A21\u5F0F\u4E0B\u5982\u4F55\u663E\u793A\u5BC6\u94A5").addDropdown((dropdown) => dropdown.addOption("blur", "\u6A21\u7CCA (\u60AC\u505C\u663E\u793A)").addOption("hidden", "\u9690\u85CF (\u70B9\u51FB\u590D\u5236)").addOption("plain", "\u660E\u6587\u663E\u793A").setValue(this.plugin.settings.placeholderStyle).onChange(async (value) => {
      this.plugin.settings.placeholderStyle = value;
      await this.plugin.saveSettings();
    }));
    this.secretSectionEl = containerEl.createDiv({ cls: "secret-management-section" });
    this.secretSectionEl.createEl("h3", { text: "\u{1F511} \u5BC6\u94A5\u7BA1\u7406" });
    this.secretSectionEl.createEl("p", {
      text: "\u52A0\u8F7D\u4E2D...",
      cls: "secret-list-loading"
    });
    this.loadSecretSection();
    containerEl.createEl("h3", { text: "\u4F7F\u7528\u8BF4\u660E" });
    const docEl = containerEl.createEl("div", { cls: "setting-item-description" });
    docEl.innerHTML = `
			<p><strong>\u5B58\u50A8\u6A21\u5F0F\u8BF4\u660E:</strong></p>
			<ul>
				<li><strong>\u672C\u5730\u6A21\u5F0F</strong>: \u4F7F\u7528\u64CD\u4F5C\u7CFB\u7EDF\u7684\u5B89\u5168\u5B58\u50A8 (macOS Keychain / Windows Credential Manager)\uFF0C\u5BC6\u94A5\u4E0D\u4F1A\u540C\u6B65\u5230\u5176\u4ED6\u8BBE\u5907</li>
				<li><strong>\u540C\u6B65\u6A21\u5F0F</strong>: \u4F7F\u7528 AES-256-GCM \u52A0\u5BC6\u5B58\u50A8\u5230 vault \u5185\u7684\u6587\u4EF6\uFF0C\u53EF\u901A\u8FC7 remotely-save \u7B49\u63D2\u4EF6\u540C\u6B65\u5230\u5176\u4ED6\u8BBE\u5907</li>
			</ul>
			<p><strong>\u5360\u4F4D\u7B26\u8BED\u6CD5:</strong></p>
			<code>{{secret:\u5BC6\u94A5ID}}</code>
			<p>\u4F8B\u5982: <code>{{secret:openai-api-key}}</code></p>
		`;
  }
  // ============================================
  // 密钥管理区块 - 异步加载
  // ============================================
  /**
   * 异步加载密钥管理区块
   */
  async loadSecretSection() {
    if (!this.secretSectionEl)
      return;
    this.secretSectionEl.empty();
    this.secretSectionEl.createEl("h3", { text: "\u{1F511} \u5BC6\u94A5\u7BA1\u7406" });
    await this.renderSecretManagement(this.secretSectionEl);
  }
  /**
   * 局部刷新密钥列表
   */
  async refreshSecretList() {
    this.editingId = null;
    await this.loadSecretSection();
  }
  /**
   * 渲染密钥管理区块
   */
  async renderSecretManagement(containerEl) {
    if (this.plugin.settings.storageMode === "sync" && !this.plugin.storageProvider.isUnlocked()) {
      new import_obsidian3.Setting(containerEl).setName("\u5BC6\u94A5\u5E93\u5DF2\u9501\u5B9A").setDesc("\u8BF7\u5148\u89E3\u9501\u5BC6\u94A5\u5E93\u4EE5\u7BA1\u7406\u5BC6\u94A5").addButton((btn) => btn.setButtonText("\u{1F513} \u89E3\u9501").setCta().onClick(() => {
        this.plugin.ensureUnlocked(() => {
          this.refreshSecretList();
        });
      }));
      return;
    }
    this.renderAddButton(containerEl);
    const secrets = await this.plugin.listSecrets();
    if (secrets.length === 0) {
      containerEl.createEl("p", {
        text: "\u6682\u65E0\u5BC6\u94A5\uFF0C\u70B9\u51FB\u4E0A\u65B9\u6309\u94AE\u6DFB\u52A0",
        cls: "secret-list-empty"
      });
      return;
    }
    const listEl = containerEl.createDiv({ cls: "secret-list" });
    for (const secretId of secrets) {
      if (this.editingId === secretId) {
        this.renderEditForm(listEl, secretId);
      } else {
        this.renderSecretItem(listEl, secretId);
      }
    }
  }
  /**
   * 渲染新增按钮
   */
  renderAddButton(containerEl) {
    new import_obsidian3.Setting(containerEl).setName("\u6DFB\u52A0\u65B0\u5BC6\u94A5").setDesc("\u5C06\u5BC6\u94A5\u5B89\u5168\u5B58\u50A8\u5230\u5BC6\u94A5\u5E93").addButton((btn) => btn.setButtonText("+ \u65B0\u589E\u5BC6\u94A5").setCta().onClick(() => {
      new SaveSecretModal(this.app, this.plugin, () => {
        this.refreshSecretList();
      }).open();
    }));
  }
  /**
   * 渲染密钥列表项
   */
  renderSecretItem(containerEl, secretId) {
    new import_obsidian3.Setting(containerEl).setName(secretId).setDesc("\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022").addButton((btn) => btn.setIcon("pencil").setTooltip("\u7F16\u8F91").onClick(() => this.startEditing(secretId))).addButton((btn) => btn.setIcon("copy").setTooltip("\u590D\u5236").onClick(() => this.copySecret(secretId))).addButton((btn) => btn.setIcon("trash").setTooltip("\u5220\u9664").setWarning().onClick(() => this.confirmDelete(secretId)));
  }
  /**
   * 渲染编辑表单
   */
  renderEditForm(containerEl, secretId) {
    const formEl = containerEl.createDiv({ cls: "secret-edit-form" });
    formEl.createEl("p", {
      text: `\u7F16\u8F91\u5BC6\u94A5: ${secretId}`,
      cls: "secret-edit-title"
    });
    let secretInput;
    let isVisible = false;
    new import_obsidian3.Setting(formEl).setName("\u65B0\u5BC6\u94A5\u503C").addText((text) => {
      secretInput = text;
      text.inputEl.type = "password";
      text.setPlaceholder("\u8F93\u5165\u65B0\u7684\u5BC6\u94A5\u503C...");
      text.inputEl.addEventListener("keydown", (e) => {
        if (e.key === "Enter") {
          e.preventDefault();
          this.saveEdit(secretId, secretInput.getValue());
        } else if (e.key === "Escape") {
          e.preventDefault();
          this.stopEditing();
        }
      });
      setTimeout(() => text.inputEl.focus(), 10);
    }).addExtraButton((btn) => btn.setIcon("eye").setTooltip("\u663E\u793A/\u9690\u85CF").onClick(() => {
      isVisible = !isVisible;
      secretInput.inputEl.type = isVisible ? "text" : "password";
      btn.setIcon(isVisible ? "eye-off" : "eye");
    }));
    new import_obsidian3.Setting(formEl).addButton((btn) => btn.setButtonText("\u4FDD\u5B58").setCta().onClick(async () => {
      await this.saveEdit(secretId, secretInput.getValue());
    })).addButton((btn) => btn.setButtonText("\u53D6\u6D88").onClick(() => this.stopEditing()));
    formEl.createEl("p", {
      text: "\u{1F4A1} Enter \u4FDD\u5B58 | Escape \u53D6\u6D88",
      cls: "secret-edit-hint"
    });
  }
  /**
   * 开始编辑
   */
  startEditing(secretId) {
    this.editingId = secretId;
    this.loadSecretSection();
  }
  /**
   * 停止编辑
   */
  stopEditing() {
    this.editingId = null;
    this.refreshSecretList();
  }
  /**
   * 保存编辑
   */
  async saveEdit(secretId, newValue) {
    if (!newValue.trim()) {
      new import_obsidian3.Notice("\u26A0\uFE0F \u8BF7\u8F93\u5165\u5BC6\u94A5\u503C");
      return;
    }
    const success = await this.plugin.saveSecret(secretId, newValue);
    if (success) {
      this.stopEditing();
    }
  }
  /**
   * 复制密钥
   */
  async copySecret(secretId) {
    const secret = await this.plugin.getSecret(secretId);
    if (secret) {
      await navigator.clipboard.writeText(secret);
      new import_obsidian3.Notice(`\u2705 \u5BC6\u94A5 "${secretId}" \u5DF2\u590D\u5236\u5230\u526A\u8D34\u677F`);
    } else {
      new import_obsidian3.Notice(`\u274C \u65E0\u6CD5\u83B7\u53D6\u5BC6\u94A5 "${secretId}"`);
    }
  }
  /**
   * 确认删除
   */
  async confirmDelete(secretId) {
    const confirmed = await new Promise((resolve) => {
      const modal = new ConfirmDeleteModal(
        this.app,
        secretId,
        (result) => resolve(result)
      );
      modal.open();
    });
    if (confirmed) {
      await this.plugin.deleteSecret(secretId);
      await this.refreshSecretList();
    }
  }
};
var ConfirmDeleteModal = class extends import_obsidian3.Modal {
  constructor(app, secretId, onConfirm) {
    super(app);
    this.secretId = secretId;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h3", { text: "\u26A0\uFE0F \u786E\u8BA4\u5220\u9664" });
    contentEl.createEl("p", {
      text: `\u786E\u5B9A\u8981\u5220\u9664\u5BC6\u94A5 "${this.secretId}" \u5417\uFF1F`
    });
    contentEl.createEl("p", {
      text: "\u6B64\u64CD\u4F5C\u4E0D\u53EF\u64A4\u9500\u3002",
      cls: "setting-item-description"
    });
    new import_obsidian3.Setting(contentEl).addButton((btn) => btn.setButtonText("\u5220\u9664").setWarning().onClick(() => {
      this.onConfirm(true);
      this.close();
    })).addButton((btn) => btn.setButtonText("\u53D6\u6D88").onClick(() => {
      this.onConfirm(false);
      this.close();
    }));
  }
  onClose() {
    this.contentEl.empty();
  }
};
